CREATE TYPE "public"."rift_side" AS ENUM('BLUE', 'RED');--> statement-breakpoint
CREATE TABLE "draft_lobbies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "draft_lobbies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shortcode" varchar,
	"blue_code" varchar(50) NOT NULL,
	"red_code" varchar(50) NOT NULL,
	"lobby_code" varchar(50) NOT NULL,
	"red_name" varchar(50) NOT NULL,
	"blue_name" varchar(50) NOT NULL,
	"b_pick_1" varchar(25),
	"b_pick_2" varchar(25),
	"b_pick_3" varchar(25),
	"b_pick_4" varchar(25),
	"b_pick_5" varchar(25),
	"r_pick_1" varchar(25),
	"r_pick_2" varchar(25),
	"r_pick_3" varchar(25),
	"r_pick_4" varchar(25),
	"r_pick_5" varchar(25),
	"b_ban_1" varchar(25),
	"b_ban_2" varchar(25),
	"b_ban_3" varchar(25),
	"b_ban_4" varchar(25),
	"b_ban_5" varchar(25),
	"r_ban_1" varchar(25),
	"r_ban_2" varchar(25),
	"r_ban_3" varchar(25),
	"r_ban_4" varchar(25),
	"r_ban_5" varchar(25),
	CONSTRAINT "draft_lobbies_shortcode_key" UNIQUE("shortcode")
);
--> statement-breakpoint
CREATE TABLE "game_dumps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game_dumps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" integer NOT NULL,
	"dump" jsonb NOT NULL,
	CONSTRAINT "game_dumps_game_id_key" UNIQUE("game_id")
);
--> statement-breakpoint
CREATE TABLE "meta" (
	"id" integer PRIMARY KEY NOT NULL,
	"season_name" varchar(20) NOT NULL,
	"provider_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "player_game_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_game_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_performance_id" integer NOT NULL,
	"kills" integer DEFAULT 0 NOT NULL,
	"deaths" integer DEFAULT 0 NOT NULL,
	"assists" integer DEFAULT 0 NOT NULL,
	"level" integer DEFAULT 0 NOT NULL,
	"gold" bigint DEFAULT 0 NOT NULL,
	"vision_score" bigint DEFAULT 0 NOT NULL,
	"damage" bigint DEFAULT 0 NOT NULL,
	"healing" bigint DEFAULT 0 NOT NULL,
	"shielding" bigint DEFAULT 0 NOT NULL,
	"damage_taken" bigint DEFAULT 0 NOT NULL,
	"self_mitigated_damage" bigint DEFAULT 0 NOT NULL,
	"damage_to_turrets" bigint DEFAULT 0 NOT NULL,
	"longest_life" bigint DEFAULT 0 NOT NULL,
	"double_kills" smallint DEFAULT 0 NOT NULL,
	"triple_kills" smallint DEFAULT 0 NOT NULL,
	"quadra_kills" smallint DEFAULT 0 NOT NULL,
	"penta_kills" smallint DEFAULT 0 NOT NULL,
	"cs" integer DEFAULT 0 NOT NULL,
	"champion_name" varchar(25) NOT NULL,
	"item0" integer,
	"item1" integer,
	"item2" integer,
	"item3" integer,
	"item4" integer,
	"item5" integer,
	"trinket" integer,
	"keystone_rune" integer NOT NULL,
	"secondary_tree" integer NOT NULL,
	"summoner1" integer NOT NULL,
	"summoner2" integer NOT NULL,
	CONSTRAINT "player_game_data_player_performance_id_key" UNIQUE("player_performance_id")
);
--> statement-breakpoint
CREATE TABLE "player_performances" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_performances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_id" integer NOT NULL,
	"game_id" integer NOT NULL,
	"team_id" integer NOT NULL,
	"division_id" integer NOT NULL,
	CONSTRAINT "player_performances_player_id_game_id_key" UNIQUE("player_id","game_id")
);
--> statement-breakpoint
CREATE TABLE "team_game_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_game_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"team_performance_id" integer NOT NULL,
	"gold" integer NOT NULL,
	"kills" integer NOT NULL,
	"side" "rift_side" NOT NULL,
	"win" boolean NOT NULL,
	"game_length" integer NOT NULL,
	"barons" integer DEFAULT 0 NOT NULL,
	"dragons" integer DEFAULT 0 NOT NULL,
	"grubs" integer DEFAULT 0 NOT NULL,
	"heralds" integer DEFAULT 0 NOT NULL,
	"towers" integer DEFAULT 0 NOT NULL,
	"inhibitors" integer DEFAULT 0 NOT NULL,
	"first_baron" boolean DEFAULT false NOT NULL,
	"first_dragon" boolean DEFAULT false NOT NULL,
	"first_grub" boolean DEFAULT false NOT NULL,
	"first_herald" boolean DEFAULT false NOT NULL,
	"first_tower" boolean DEFAULT false NOT NULL,
	"first_inhibitor" boolean DEFAULT false NOT NULL,
	"first_blood" boolean DEFAULT false NOT NULL,
	CONSTRAINT "team_game_data_team_performance_id_key" UNIQUE("team_performance_id")
);
--> statement-breakpoint
CREATE TABLE "team_performances" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_performances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"team_id" integer,
	"game_id" integer,
	"division_id" integer,
	CONSTRAINT "team_performances_team_id_game_id_key" UNIQUE("team_id","game_id")
);
--> statement-breakpoint
CREATE TABLE "team_to_series" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"series_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "accounts" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "group_keys" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "results" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "schedules" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "standings" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "accounts" CASCADE;--> statement-breakpoint
DROP TABLE "group_keys" CASCADE;--> statement-breakpoint
DROP TABLE "results" CASCADE;--> statement-breakpoint
DROP TABLE "schedules" CASCADE;--> statement-breakpoint
DROP TABLE "standings" CASCADE;--> statement-breakpoint
ALTER TABLE "divisions" DROP CONSTRAINT "divisions_tournament_id_key";--> statement-breakpoint
ALTER TABLE "players" DROP CONSTRAINT "players_primary_riot_puuid_key";--> statement-breakpoint
ALTER TABLE "players" DROP CONSTRAINT "players_summoner_name_key";--> statement-breakpoint
ALTER TABLE "series" DROP CONSTRAINT "series_team1_id_team2_id_playoffs_key";--> statement-breakpoint
ALTER TABLE "games" DROP CONSTRAINT "games_winner_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "games" DROP CONSTRAINT "games_loser_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "games" DROP CONSTRAINT "games_series_id_series_id_fk";
--> statement-breakpoint
ALTER TABLE "games" DROP CONSTRAINT "games_result_id_results_id_fk";
--> statement-breakpoint
ALTER TABLE "players" DROP CONSTRAINT "players_team_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "series" DROP CONSTRAINT "series_team1_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "series" DROP CONSTRAINT "series_team2_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "series" DROP CONSTRAINT "series_winner_id_teams_id_fk";
--> statement-breakpoint
ALTER TABLE "teams" DROP CONSTRAINT "teams_division_id_divisions_id_fk";
--> statement-breakpoint
ALTER TABLE "teams" DROP CONSTRAINT "teams_captain_id_players_id_fk";
--> statement-breakpoint
DROP INDEX "divisions_lower_idx";--> statement-breakpoint
DROP INDEX "players_primary_riot_puuid_idx";--> statement-breakpoint
DROP INDEX "teams_lower_idx";--> statement-breakpoint
ALTER TABLE "games" ALTER COLUMN "game_num" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "games" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "games" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;--> statement-breakpoint
ALTER TABLE "games" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "players" ALTER COLUMN "summoner_name" SET DATA TYPE varchar(25);--> statement-breakpoint
ALTER TABLE "series" ALTER COLUMN "playoffs" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "name" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "division_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "teams" ALTER COLUMN "logo" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "shortcode" varchar(100) NOT NULL;--> statement-breakpoint
ALTER TABLE "games" ADD COLUMN "callback_result" jsonb;--> statement-breakpoint
ALTER TABLE "players" ADD COLUMN "riot_puuid" char(78) NOT NULL;--> statement-breakpoint
ALTER TABLE "series" ADD COLUMN "division_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "series" ADD COLUMN "loser_id" integer;--> statement-breakpoint
ALTER TABLE "draft_lobbies" ADD CONSTRAINT "draft_lobbies_shortcode_fkey" FOREIGN KEY ("shortcode") REFERENCES "public"."games"("shortcode") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_dumps" ADD CONSTRAINT "game_dumps_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_game_data" ADD CONSTRAINT "player_game_data_player_performance_id_fkey" FOREIGN KEY ("player_performance_id") REFERENCES "public"."player_performances"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_performances" ADD CONSTRAINT "player_performances_division_id_fkey" FOREIGN KEY ("division_id") REFERENCES "public"."divisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_performances" ADD CONSTRAINT "player_performances_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_performances" ADD CONSTRAINT "player_performances_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player_performances" ADD CONSTRAINT "player_performances_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_game_data" ADD CONSTRAINT "team_game_data_team_performance_id_fkey" FOREIGN KEY ("team_performance_id") REFERENCES "public"."team_performances"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_performances" ADD CONSTRAINT "team_performances_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_performances" ADD CONSTRAINT "team_performances_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_to_series" ADD CONSTRAINT "fk_series_id" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_to_series" ADD CONSTRAINT "fk_team_id" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "fk_loser_id" FOREIGN KEY ("loser_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "fk_series_id" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "fk_winner_id" FOREIGN KEY ("winner_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "fk_team_id" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "fk_loser_id" FOREIGN KEY ("loser_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "fk_winner_id" FOREIGN KEY ("winner_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_division_id_fkey" FOREIGN KEY ("division_id") REFERENCES "public"."divisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "fk_captain_id" FOREIGN KEY ("captain_id") REFERENCES "public"."players"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "fk_division_id" FOREIGN KEY ("division_id") REFERENCES "public"."divisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "divisions" DROP COLUMN "description";--> statement-breakpoint
ALTER TABLE "divisions" DROP COLUMN "provider_id";--> statement-breakpoint
ALTER TABLE "divisions" DROP COLUMN "groups";--> statement-breakpoint
ALTER TABLE "games" DROP COLUMN "short_code";--> statement-breakpoint
ALTER TABLE "games" DROP COLUMN "result_id";--> statement-breakpoint
ALTER TABLE "games" DROP COLUMN "processed";--> statement-breakpoint
ALTER TABLE "players" DROP COLUMN "primary_riot_puuid";--> statement-breakpoint
ALTER TABLE "series" DROP COLUMN "team1_id";--> statement-breakpoint
ALTER TABLE "series" DROP COLUMN "team2_id";--> statement-breakpoint
ALTER TABLE "series" DROP COLUMN "message_id";--> statement-breakpoint
ALTER TABLE "series" DROP COLUMN "win_condition";--> statement-breakpoint
ALTER TABLE "teams" DROP COLUMN "group_id";--> statement-breakpoint
ALTER TABLE "divisions" ADD CONSTRAINT "divisions_name_key" UNIQUE("name");--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_shortcode_key" UNIQUE("shortcode");--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_riot_puuid_key" UNIQUE("riot_puuid");--> statement-breakpoint
DROP TYPE "public"."aal_level";--> statement-breakpoint
DROP TYPE "public"."action";--> statement-breakpoint
DROP TYPE "public"."code_challenge_method";--> statement-breakpoint
DROP TYPE "public"."equality_op";--> statement-breakpoint
DROP TYPE "public"."factor_status";--> statement-breakpoint
DROP TYPE "public"."factor_type";--> statement-breakpoint
DROP TYPE "public"."key_status";--> statement-breakpoint
DROP TYPE "public"."key_type";--> statement-breakpoint
DROP TYPE "public"."one_time_token_type";